/** @format */
export const EMPLOYER_LIKED_ADD = "employer/EMPLOYER_LIKED_ADD";
export const EMPLOYER_LIKED_REMOVE = "employer/EMPLOYER_LIKED_REMOVE";
export const EMPLOYER_COMPANY_EDIT = "employer/EMPLOYER_COMPANY_EDIT";
export const EMPLOYER_COMPANY_ADD = "employer/EMPLOYER_COMPANY_ADD";
export const EMPLOYER_COMPANY_REMOVE = "employer/EMPLOYER_REMOVE";
export const EMPLOYER_BOOKMARK_EDIT = "employer/BOOKMARK_EDIT";
export const EMPLOYER_BOOKMARK_ADD = "employer/BOOKMARK_ADD";
export const EMPLOYER_BOOKMARK_REMOVE = "employer/BOOKMARK_REMOVE";

export const MATCHING_ALL_INFO_GET = "matching/MATCHING_ALL_INFO_GET";
export const MATCHING_PROGRAMMING_INFO_GET = "matching/PROGRAMMING_INFO_GET";
export const MATCHING_DATA_SCIENCE_INFO_GET =
  "matching/MATCHING_DATA_SCIENCE_INFO_GET";
export const MATCHING_MARKETING_INFO_GET = "matching/_MARKETING_INFO_GET";
export const MATCHING_DESIGN_INFO_GET = "matching/MATCHING_DESIGN_INFO_GET";

//////EMPLOYEE

export const EMPLOYEE_INFO_GET = "employee/EMPLOYEE_INFO_GET";
export const EMPLOYEE_INFO_SUCCESS = "employee/EMPLOYEE_INFO_SUCCESS";
export const EMPLOYEE_INFO_FAILURE = "employee/EMPLOYEE_INFO_FAILURE";

export const EMPLOYEE_RESUME_GET = "employee/EMPLOYEE_RESUME_GET";
export const EMPLOYEE_RESUME_SUCCESS = "employee/EMPLOYEE_RESUME_SUCCESS";
export const EMPLOYEE_RESUME_FAILURE = "employee/EMPLOYEE_RESUME_FAILURE";

export const EMPLOYEE_RESUME_EDIT = "employee/EMPLOYEE_RESUME_EDIT";

export const EMPLOYEE_ID_GET_REQUEST = "employer/EMPLOYEE_ID_GET_REQUEST";
export const EMPLOYEE_ID_GET_SUCCESS = "employer/EMPLOYEE_ID_GET_SUCCESS";
export const EMPLOYEE_ID_GET_FAILURE = "employer/EMPLOYEE_ID_GET_FAILURE";

///PROJECT

export const PROJECT_INFO_GET = "project/PROJECT_INFO_GET";

export const TEACHER_INFO_GET = "teacher/TEACHER_INFO_GET";
export const TEACHER_INFO_EDIT = "teacher/TEACHER_INFO_EDIT";
export const TEACHER_COMMENT_EDIT = "teacher/TEACHER_COMMENT_EDIT";
export const TEACHER_COMMENT_ADD = "teacher/TEACHER_INFO_GET";
export const TEACHER_COMMENT_REMOVE = "teacher/TEACHER_COMMENT_REMOVE";
